### ISSUE TITLE
Issues in avi_customipamdnsprofile when using PATCH operations

### ISSUE THREAD

**Issue by itaytalmi** [avinetworks/ansible-role-avisdk#229]
When attempting to use the `avi_customipamdnsprofile` module using PATCH operations (see example below), there seems to be an issue and I think it's an API-level issue.

Environment:
AVISDK role version: `21.1.2`
AVI Controller version: `20.1.6`
Ansible version: `2.12.1`

Here is a `playbook.yml` YAML file that can be used to reproduce the issue:

```yaml
---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    nsx_alb_host: 10.100.135.202
    nsx_alb_username: admin
    nsx_alb_password: VMware1!
    nsx_alb_api_version: 20.1.6
    nsx_alb_ipam_profile_name: tkg-vip-ipam-profile
    nsx_alb_new_network_ref: "https://10.100.135.202/api/network/dvportgroup-8014-cloud-56603465-9252-4cbe-9304-69a365cd9538"
  tasks:
    - name: Update IPAM Profile Usable Networks
      avi_ipamdnsproviderprofile:
        controller: "{{ nsx_alb_host }}"
        username: "{{ nsx_alb_username }}"
        password: "{{ nsx_alb_password }}"
        api_version: "{{ nsx_alb_api_version }}"
        avi_api_update_method: patch
        avi_api_patch_op: add
        name: "{{ nsx_alb_ipam_profile_name }}"
        type: IPAMDNS_TYPE_INTERNAL
        internal_profile:
          usable_networks:
            - nw_ref: "{{ nsx_alb_new_network_ref }}"
```

The returned error message:

```text
('HTTP Error: 400 Error Msg {\"error\": \"Failed to patch list of sub objects. Key not found.\"}
```

**After investigating this, I don't think it's an Ansible issue.
I've tried to invoke the same operation using Postman (but obviously you can see the issue from any REST API client) and got the same error message.

The following can be used to reproduce the issue using Postman:

Request method: `PATCH`
Request URL: `https://{{ nsx_alb_host }}/api/ipamdnsproviderprofile/{{ ipam_profile_uuid }}`

Request headers:`X-Avi-Version: 20.1.6`, `Content-Type: application/json`

Request body (replace with your network ref object URL):

```json
{
    "add": {
        "internal_profile": {
            "usable_networks": [
                {
                    "nw_ref": "https://10.100.135.202/api/network/dvportgroup-8014-cloud-56603465-9252-4cbe-9304-69a365cd9538"
                }
            ]
        }
    }
}
```

The returned error in Postman:

```text
Status: 400 BAD REQUEST
{
    "error": "Failed to patch list of sub objects. Key not found."
}
```

The strange thing is, if you run the same request with the following body (omitting the `internal_profile` field):

```json
{
    "add": {
        "usable_networks": [
            {
                "nw_ref": "https://10.100.135.202/api/network/dvportgroup-8014-cloud-56603465-9252-4cbe-9304-69a365cd9538"
            }
        ]
    }
}
```

You will receive status code 200 and response containing the IPAM Profile JSON object although nothing has actually changed... Same thing for `delete` or `replace` operations using `PATCH`.

Reference:
HTTP PATCH support: https://avinetworks.com/docs/20.1/api-http-patch-support
Avi IpamDnsProviderProfile Object API: https://avinetworks.com/docs/latest/api-guide/IpamDnsProviderProfile/index.html

As a temporary workaround, I retrieved the current IPAM Profile JSON object, appended the relevant network refs to the `usable_networks` array, and used a `PUT` request. However, it would be much better to be able to use your module to natively add the networks instead of having to use JSON manipulation for this purpose...

My workaround:

```yaml
---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    nsx_alb_host: 10.100.135.202
    nsx_alb_username: admin
    nsx_alb_password: VMware1!
    nsx_alb_api_version: 20.1.6
    nsx_alb_ipam_profile_name: tkg-vip-ipam-profile
    nsx_alb_new_network_name: tkg-wld-01-controlplane
  tasks:
    - name: Get NSX ALB IPAM Profile
      uri:
        url: "https://{{ nsx_alb_host }}/api/ipamdnsproviderprofile?name={{ nsx_alb_ipam_profile_name }}"
        validate_certs: no
        url_username: "{{ nsx_alb_username }}"
        url_password: "{{ nsx_alb_password }}"
        force_basic_auth: yes
        method: GET
        return_content: yes
        headers:
          Content-Type: application/json
          X-Avi-Version: "{{ nsx_alb_api_version }}"
      register: nsx_alb_ipam_profile

    - name: Set Fact - NSX ALB IPAM Profile JSON Object
      set_fact:
       ipam_profile_json: "{{ nsx_alb_ipam_profile.json.results[0] }}"

    - name: Get NSX ALB Network Object
      uri:
        url: "https://{{ nsx_alb_host }}/api/network?name={{ nsx_alb_new_network_name }}"
        validate_certs: no
        url_username: "{{ nsx_alb_username }}"
        url_password: "{{ nsx_alb_password }}"
        force_basic_auth: yes
        method: GET
        return_content: yes
        headers:
          Content-Type: application/json
          X-Avi-Version: "{{ nsx_alb_api_version }}"
      register: nsx_alb_network

    - name: Set Fact - NSX ALB Network Object URL
      set_fact:
        ipam_profile_json_addition:
          internal_profile:
            usable_networks:
              - nw_ref: "{{ nsx_alb_network.json.results[0].url }}"

    - name: Set Fact - Update NSX ALB IPAM Profile JSON Object
      set_fact:
        ipam_profile_json: "{{ ipam_profile_json | combine(ipam_profile_json_addition, recursive=true, list_merge='append_rp') }}"

    - name: Update NSX ALB IPAM Profile
      uri:
        url: "https://{{ nsx_alb_host }}/api/ipamdnsproviderprofile/{{ ipam_profile_json.uuid }}"
        validate_certs: no
        url_username: "{{ nsx_alb_username }}"
        url_password: "{{ nsx_alb_password }}"
        force_basic_auth: yes
        method: PUT
        body: "{{ ipam_profile_json }}"
        body_format: json
        return_content: yes
        headers:
          Content-Type: application/json
          X-Avi-Version: "{{ nsx_alb_api_version }}"
```

I have also tried AVI controller version `21.1.2` and encountered the same issue.
